# Generated by Django 5.2.7 on 2025-10-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InformeMantenimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipo", models.CharField(max_length=200)),
                ("numero_serie", models.CharField(max_length=100)),
                ("ubicacion", models.CharField(max_length=200)),
                (
                    "tipo_mantenimiento",
                    models.CharField(
                        choices=[
                            ("preventivo", "Preventivo"),
                            ("correctivo", "Correctivo"),
                            ("predictivo", "Predictivo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_mantenimiento", models.DateField()),
                ("tecnico", models.CharField(max_length=100)),
                ("descripcion_trabajo", models.TextField()),
                ("materiales_utilizados", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("proximo_mantenimiento", models.DateField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
