# Generated by Django 5.2.7 on 2025-10-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mantenimiento_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="informemantenimiento",
            name="alcance",
            field=models.CharField(default="-20,0 °C a 150,0 °C", max_length=100),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="cliente",
            field=models.CharField(
                default="TECNOLÓGICA DE ALIMENTOS S.A.", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="direccion",
            field=models.TextField(
                default="Panamericana Sur km 61 Fnd. La Quipa (Lima/Lima/Pucusana)"
            ),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="division",
            field=models.CharField(default="0,1 °C", max_length=50),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="frecuencia",
            field=models.CharField(default="60 Hz", max_length=50),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="identificacion",
            field=models.CharField(default="CHI-002", max_length=100),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="intensidad",
            field=models.CharField(default="No indica", max_length=50),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="marca",
            field=models.CharField(default="JULABO", max_length=100),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="modelo",
            field=models.CharField(default="F12 - EH", max_length=100),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="orden_trabajo",
            field=models.CharField(default="OT-02502645", max_length=50),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="procedencia",
            field=models.CharField(default="Alemania", max_length=100),
        ),
        migrations.AddField(
            model_name="informemantenimiento",
            name="tension",
            field=models.CharField(default="230 v", max_length=50),
        ),
    ]
