# Generated by Django 5.2.7 on 2025-10-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mantenimiento_app", "0002_informemantenimiento_alcance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informemantenimiento",
            name="alcance",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="cliente",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="direccion",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="division",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="frecuencia",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="identificacion",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="intensidad",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="marca",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="modelo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="orden_trabajo",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="procedencia",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="informemantenimiento",
            name="tension",
            field=models.CharField(max_length=50),
        ),
    ]
